front-end:
  image: weaveworksdemos/front-end
  hostname: front-end
  restart: always
edge-router:
  image: weaveworksdemos/edge-router
  ports:
    - ${FRONTEND_PORT}:80
    - ${TRAFFIK_PORT}:8080
  hostname: edge-router
  restart: always
catalogue:
  image: weaveworksdemos/catalogue
  hostname: catalogue
  restart: always
catalogue-db:
  image: weaveworksdemos/catalogue-db
  hostname: catalogue-db
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=socksdb
carts:
  image: weaveworksdemos/carts
  hostname: carts
  restart: always
  environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
carts-db:
  image: mongo
  hostname: carts-db
  restart: always
orders:
  image: weaveworksdemos/orders
  hostname: orders
  restart: always
  environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
orders-db:
  image: mongo
  hostname: orders-db
  restart: always
shipping:
  image: weaveworksdemos/shipping
  hostname: shipping
  restart: always
  environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
queue-master:
  image: weaveworksdemos/queue-master
  hostname: queue-master
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
rabbitmq:
  image: rabbitmq:3.12.13
  hostname: rabbitmq
  restart: always
payment:
  image: weaveworksdemos/payment
  hostname: payment
  restart: always
user:
  image: weaveworksdemos/user
  hostname: user
  restart: always
  environment:
    - MONGO_HOST=user-db:27017
user-db:
  image: weaveworksdemos/user-db
  hostname: user-db
  restart: always
user-sim:
  image: weaveworksdemos/load-test
  hostname: user-simulator
  command: "-d 60 -r 200 -c 2 -h edge-router"
