.catalog:
  name: "Jenkins"
  version: 2.87
  description: "Jenkins CI/CD 2.*"
  uuid: jenkins-0
  minimum_rancher_version: v1.6.0
  questions:
    - variable: JENKINS_MEM_LIMIT
      label: 'rancher mem_limit param'
      required: true
      default: "8589934592"
      type: int
    - variable: JENKINS_MEM_RESERVATION
      label: 'rancher mem_reservation param'
      required: true
      default: "8589934592"
      type: int
    - variable: JENKINS_CONTAINER_HOSTNAME
      label: 'Jenkins Dockercontainer Hostname'
      required: true
      default: "jenkins-ops"
      type: string
    - variable: JENKINS_FQDN_LB
      label: 'Jenkins FQDN for expose via LB'
      required: true
      default: "jenkins.service.int.example.cloud"
      type: string
    - variable: JENKINS_HOME_VOL
      label: 'Jenkins home volume for workspaces'
      required: true
      default: "jenkins"
      type: string
    - variable: LOADBALANCING
      label: 'Activate loadbalacing via HAPROXY'
      required: true
      default: "true"
      type: enum
      options:
        - true
        - false
    - variable: VOLUME_DRIVER
      label: 'Volume driver'
      required: true
      default: 'rancher-nfs'
      type: enum
      options:
        - local
        - convoy-nfs
        - rancher-nfs
jenkins:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - hostname: ${JENKINS_FQDN_LB}
      path: /
      target_port: 8080
