.catalog:
  name: "Loadbalancer"
  version: 0.7.3
  description: "domain driven haproxy entry loadbalancer"
  uuid: loadbalancer-0
  minimum_rancher_version: v1.6.0
  questions:
    - variable: HAPROXY_SOURCE_PORT
      label: 'SOURCE_PORT'
      required: true
      default: "80"
      type: int
    - variable: HAPROXY_EXPOSE_PORT
      label: 'EXPOSE_PORT'
      required: true
      default: "80"
      type: int
    - variable: HAPROXY_TARGET_PORT
      label: 'TARGET_PORT'
      required: true
      default: "80"
      type: int
    - variable: HAPROXY_PROTOCOL
      label: 'HAPROXY_PROTOCOL'
      required: true
      default: "http"
      type: string
    - variable: GLOBAL_SCHEDULING
      label: 'rancher global scheduling'
      required: true
      default: "true"
      type: enum
      options:
        - true
        - false
loadbalancer:
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: ${HAPROXY_PROTOCOL}
      selector: lb=true
      source_port: ${HAPROXY_SOURCE_PORT}
      target_port: ${HAPROXY_TARGET_PORT}
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
